---

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 379CE192D401AB61
    state: present

- name: add Etcher repo
  apt_repository: repo='deb https://dl.bintray.com/resin-io/debian stable etcher' state=present

- name: Install etcher
  apt: name=etcher-electron state=present update_cache=yes
