---

- name: Add Conky Manager repository
  apt_repository:
    repo: ppa:teejee2008/ppa
    state: present


- name: Install Conky Manager
  apt:
    name: conky-manager
    state: present
    update_cache: yes
