---

- name: Installing Basic Packages (vim,iftop, unity tweak, dconf editor)
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
      - vim
      - iftop
      - unity-tweak-tool
      - dconf-editor
      - ubuntu-restricted-addons
      - unzip
      - unrar
      - ubuntu-restricted-extras
      - htop
      - apt-transport-https
