---

- name: Add Webmin key
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    keyring: /etc/apt/trusted.gpg.d/jcameron-key.gpg
    state: present
  when: ansible_distribution == 'Ubuntu'
  register: webminkey

- name: add Webmin repo
  apt_repository: repo='deb https://download.webmin.com/download/repository sarge contrib' state=present
  when: webminkey.changed
  register: webminrepo

- name: Install Webmin
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - perl
    - libnet-ssleay-perl
    - openssl
    - libauthen-pam-perl
    - libpam-runtime
    - libio-pty-perl
    - apt-show-versions python
  when: webminrepo.changed
