---

- name: Add Webmin key
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    keyring: /etc/apt/trusted.gpg.d/jcameron-key.gpg
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_architecture == 'x86_64'

- name: add Webmin repo
  apt_repository: repo='deb https://download.webmin.com/download/repository sarge contrib' state=present
- apt_repository: repo=' http://download.webmin.com/download/repository sarge contrib' state=present

- name: Install Webmin
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - perl
    - libnet-ssleay-perl
    - openssl
    - libauthen-pam-perl
    - libpam-runtime
    - libio-pty-perl
    - apt-show-versions python
