---

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: add Google Chrome repo
  apt_repository: repo='deb https://download.sublimetext.com/ apt/stable/' state=present

- name: Install latest sublime package
  apt: name=sublime-text state=present update_cache=yes
