---

- name: Download and extract eclipse 4.6 Oxygen Kepler
  unarchive:
    src: "{{ eclipse_dwn }}"
    dest: /usr/local/
    remote_src: yes
    state: present

- name: Add Symlink
  shell: ln -s /usr/local/eclipse/eclipse /usr/local/bin/eclipse
