---

# - name: Download Eclipse IDE to HOME
#   get_url:
#     url: "{{ eclipse_dwn }}"
#     dest: "{{ ansible_env.HOME }}"
#     state: present

- name: Download and extract eclipse 4.6 Oxygen
  unarchive:
    src: "{{ eclipse_dwn }}"
    dest: /usr/local/
    remote_src: yes
    state: present

- name: Add Symlink
  shell: ln -s /usr/local/eclipse/eclipse /usr/local/bin/eclipse
