---

- name: Add Albert repository
  apt_repository: repo='ppa:nilarimogard/webupd8' state="{{ albert.repo }}"

- name: Install Albert
  apt: name=albert state="{{ albert.install }}" update_cache=yes
