---

- name: Visual Studio Code for 32 BIT
  apt: deb="https://az764295.vo.msecnd.net/stable/c63189deaa8e620f650cc28792b8f5f3363f2c5b/code_1.20.0-1518023590_i386.deb" state=present
  when: ansible_distribution == 'Ubuntu' and ansible_architecture == 'i386' and ansible_architecture == 'i686'

- name: Add VSCODE Key File
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_architecture == 'x86_64'
  register: vscodekey

- name: add Visual Studio Code repo
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main' state=present
  when: vscodekey.changed
  register: vscoderepo

- name: Install Visual Studio Code
  apt: name=code state=latest update_cache=yes
  when: vscoderepo.changed
