---

- name: Check if TeamViewer is installed
  command: dpkg-query -W teamviewer
  register: teamviewer_check_deb
  failed_when: teamviewer_check_deb.rc > 1
  changed_when: teamviewer_check_deb.rc == 1

- name: Install TeamViewer dependencies
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - libjpeg62
    - libxinerama1
    - libxrandr2
    - libxtst6

- name: Install TeamViewer
  apt: deb="https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
  when: ansible_architecture=x86_64
